### ISSUE TITLE
Add "About OrgManager" to README

### ISSUE THREAD

**Issue by richb-hanover** [orgmanager/orgmanager#188]
## Expected Behavior
A friend sent a link to this repo. I don't know what OrgManager is. I hoped I could find out.

## Current Behavior
The README gives pretty good information about how to set up OrgManager, but misses out on a project description.

## Possible Solution
Add some description about what OrgManager is, what it might do for me (or link to an existing page that does this. Good luck

## Context

Newcomers / Documentation

**Comment by m1guelpf** [comment]
@richb-hanover Please take a look at [this article](https://medium.com/@m1guelpf/orgmanager-free-invite-system-for-your-github-orgs-4dd6c96a3a6) until I add the info to the repo. Also, thanks for pointing it out instaed of leaving?

**Comment by richb-hanover** [comment]
Thanks for the speedy response. My motto is, "We promise not to fix it if we don't know it's broke..." :-)

A thought: Put a link to that Medium article at the top of the repo info, next to the text "Take Github Organizations to a new level!" That would have sufficed for me.

Good luck!

**Comment by m1guelpf** [comment]
@richb-hanover Thank you again!
I think I'll keep this open until it's added, if you don't mind.

**Comment by richb-hanover** [comment]
Fine with me. Cheers!
