### ISSUE TITLE
Logos need to be updated

### ISSUE THREAD

**Issue by simonv3** [orgmanager/orgmanager#241]
## Expected Behavior

When our orgs logo updates, it should update the logo on orgmanager after clicking on "Sync" under "sync organization"

## Current Behavior

It doesn't sync the logo.

## Possible Solution

When clicking on Sync the logo should be updated. Possibly it's being cached somewhere?

## Steps to Reproduce (for bugs)

1. Get an organization on GitHub
2. Set the logo of the organization
3. Sign up with orgmanager and link the organization
4. Change the logo of the organization on GitHub
5. Logo isn't updated on orgmanager

## Context

Open Source Design recently changed their logo https://github.com/opensourcedesign/

It's not updated here https://orgmanager.miguelpiedrafita.com/join/4183553

**Comment by m1guelpf** [comment]
@simonv3 Working on it now, should be fixed one #242 is merged.

**Comment by m1guelpf** [comment]
@simonv3 Should be fixed now

**Comment by simonv3** [comment]
It's still a circle for me after clicking "Sync" a couple of times :( 

https://orgmanager.miguelpiedrafita.com/join/4183553

**Comment by m1guelpf** [comment]
@simonv3 Could you please clear the cache and try again?

**Comment by m1guelpf** [comment]
@simonv3 Seems to be a cache issue, try to open the image in a new tab and you'll see the new one

**Comment by simonv3** [comment]
@m1guelpf I did, also looked at it in incognito and a different browser (safari, which I never use) and they're all still the circle.

**Comment by m1guelpf** [comment]
@simonv3 Will have a closer look later
