### ISSUE TITLE
Switch to Socialite

### ISSUE THREAD

**Issue by m1guelpf** [orgmanager/orgmanager#249]
## Expected Behavior

OrgManager allows login with GitHub without hardcoded scopes.

## Current Behavior

The scopes must be hardcoded.

## Possible Solution

Switch to Laravel Socialite

## Context

Would allow #121 & #56

## Your Environment

* Version used: OrgManager Developer Version

* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): PHP 7.1 on hotel 0.7.1

* Operating System and version: Ubuntu 16.10

**Comment by VictorAvelar** [comment]
Have you tried on this?

https://github.com/adamwathan/eloquent-oauth-l5

It is simple as dead.

**Comment by joffreycarle** [comment]
Hi! Just saw your project on up-for-grabs and wondering if I could help on this issue? I've played a little with the project and it seems you almost managed Socialite on master branch?

**Comment by m1guelpf** [comment]
@joffreycarle Sorry, but I finally managed to migrate to Socialite, and forgot to close the issue 😞 
If you want to help at OrgManager, I recommend to have a look at the open issues, and check the [Contributing page](https://orgmanager.readme.io/docs/contributing-to-orgmanager) in the OrgManager Documentation.
