### ISSUE TITLE
Require login to get invite

### ISSUE THREAD

**Issue by gautamkrishnar** [orgmanager/orgmanager#277]
## Expected Behavior
I must be able to send invitations to my own account

## Current Behavior
I can just type anyone's username and send the invite to n number of people

## Possible Solution
Make logging in mandatory. Check username entered == Logged in user's username

## Steps to Reproduce (for bugs)

1. Add organization to orgmanager

2. Generate an invite link

3. Type random username after visiting invite link

4. It works!

**Comment by m1guelpf** [comment]
I'll look into this

**Comment by gautamkrishnar** [comment]
:+1:

**Comment by 0x48piraj** [comment]
Why don't just use the **in-built** feature! :smiley: 

> *Reference :* https://help.github.com/articles/inviting-users-to-join-your-organization/

**Comment by m1guelpf** [comment]
@0x48piraj For future reference, this issue was refering to a previous version of OrgManager, where you could enter anyone's username and they'd instanty get an invite. Now, you have to login with GitHub to get one 😄

**Comment by 0x48piraj** [comment]
> I can just type anyone's username and send the invite to n number of people

**This line got me thinking** :smiley_cat:
