### ISSUE TITLE
Client error: `GET https://api.github.com/user?access_token=` resulted in a `401 Unauthorized` re... in GET /callback

### ISSUE THREAD

**Issue by m1guelpf** [orgmanager/orgmanager#290]
## Error in OrgManager

**Client error: `GET https://api.github.com/user?access_token=` resulted in a `401 Unauthorized` re...** in **GET /callback**
Client error: `GET https://api.github.com/user?access_token=` resulted in a `401 Unauthorized` response:
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}

[View on Bugsnag](https://app.bugsnag.com/mp-4/orgmanager/errors/59aea5d65114af001a0fa2fd?event_id=59aea5d65114af001a0fa2fc&i=gh&m=ci)

## Stacktrace

    app/Exceptions/Handler.php:40 - App\Exceptions\Handler::report
    app/Http/Middleware/RedirectIfAuthenticated.php:25 - App\Http\Middleware\RedirectIfAuthenticated::handle
    app/Http/Middleware/HttpsMiddleware.php:23 - App\Http\Middleware\HttpsMiddleware::handle

[View full stacktrace](https://app.bugsnag.com/mp-4/orgmanager/errors/59aea5d65114af001a0fa2fd?event_id=59aea5d65114af001a0fa2fc&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by m1guelpf** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Client error: `GET https://api.github.com/user?access_token=` resulted in a `401 Unauthorized` re...** in **GET /callback**](https://app.bugsnag.com/mp-4/orgmanager/errors/59aea5d65114af001a0fa2fd?event_id=59aea5d65114af001a0fa2fc&i=gh&m=fx)

**Comment by leonardsangoroh** [comment]
Thanks for the link, it would be better if you'd just phrase the response here soo that others don't have to sign in to a one-time site
