### ISSUE TITLE
Design is broken and organization sync gives error

### ISSUE THREAD

**Issue by mariobehling** [orgmanager/orgmanager#313]
## Expected Behavior

A standard UI and working sync.

## Current Behavior

Design broken. See screenshot below.

## Possible Solution

Check CSS/HTML.

## Steps to Reproduce (for bugs)

1. Go to dashboard

2. Click on organization settings

3. See the broken design

4. Click on "Sync" (https://orgmanager.miguelpiedrafita.com/sync). An error message appears.

## Link to your project:
https://github.com/fossasia

![screenshot from 2017-12-17 11-18-02](https://user-images.githubusercontent.com/1583873/34078528-6c3ec042-e31c-11e7-940b-7d5e5120b7b2.png)

**Comment by m1guelpf** [comment]
@mariobehling Thank you for reporting this. The design problem will be fixed soon, I suppose I broke something when working on the redesign... the sync issue it's a little more strange ([for future reference, here's the stack trace](https://sentry.io/share/issue/7ec1630d09d94534848257576184bdcc/)), as it seems like GitHub API 404s when getting org info. I'll contact GitHub Support regarding this, but it'd be helpful if you could sync all the organizations from the main dashboard and try again.

**Comment by mariobehling** [comment]
@m1guelpf Thanks. There does not seem to be an option to sync from the main dashboard. The only link I have is https://orgmanager.miguelpiedrafita.com/sync.

**Comment by m1guelpf** [comment]
@mariobehling The dashboard (orgmanager.miguelpiedrafita.com/dashboard) should have a blue button that says "sync all organizations")

**Comment by mariobehling** [comment]
Ok, found it by changing the resolution. In small resolution it is hidden under the top bar and cannot be scrolled to.

![screenshot from 2017-12-17 14-09-48](https://user-images.githubusercontent.com/1583873/34079753-0cadedfc-e334-11e7-9f39-a598e9ff7cc8.png)

**Comment by m1guelpf** [comment]
@mariobehling Does the design work now?

**Comment by mariobehling** [comment]
Thanks. The link to sync does not work, but hitting the sync button seems to work. Thank you!
