### ISSUE TITLE
No vendor folder in the app's directory

### ISSUE THREAD

**Issue by NishSatish** [orgmanager/orgmanager#315]
## Expected Behavior

There must be a vendor folder in every laravel 5 app, however it is missing here. It is where all the extensions are installed, including laravel-collective for forms.

* Version used: Laravel 5

* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): PHP 5.6

* Operating System and version: Windows 7

**Comment by m1guelpf** [comment]
@NishSatish You need to run `composer install` to get the folder
