### ISSUE TITLE
API Support?

### ISSUE THREAD

**Issue by TiagoDanin** [orgmanager/orgmanager#319]
Is there an API?
I found [this](https://github.com/orgmanager/php-orgmanager-api) repo, but does not work.
https://orgmanager.miguelpiedrafita.com/api is redirected to https://orgmanager.miguelpiedrafita.com/dashboard

**Comment by m1guelpf** [comment]
@TiagoDanin Yes, we do have an API. You can check the docs [here](https://docs.orgmanager.miguelpiedrafita.com).

The only thing you need to know is that you'll need an API token to make any request, and if you don't provide one, you'll be redirected to the login (or to the dashboard, if you are logged in). You can get your token [here](https://orgmanager.miguelpiedrafita.com/developer).

**Comment by TiagoDanin** [comment]
Thank!
