### ISSUE TITLE
css access directory/file listing

### ISSUE THREAD

**Issue by ismailtasdelen** [orgmanager/orgmanager#383]
## Expected Behavior

Directory listing

## Current Behavior

Directory listing

## Possible Solution

The directory is not listed.

## Steps to Reproduce (for bugs)

1. https://orgmanager.miguelpiedrafita.com/css/

## Context

Do you It is an appropriate security vulnerability to report on HackerOne.

## Your Environment

https://orgmanager.miguelpiedrafita.com/dashboard

* Version used: The OrgManager Hosted Version.

* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):

* Server type and version:

* Operating System and version:

* Link to your project: https://orgmanager.miguelpiedrafita.com/dashboard

**Comment by m1guelpf** [comment]
Fixed https://github.com/orgmanager/orgmanager/commit/7222e1e7d0209164af3b0f445ff2f1692cefcdbf

**Comment by ismailtasdelen** [comment]
Thanks for the came back :100: :+1:
