### ISSUE TITLE
Hosted version unvailable

### ISSUE THREAD

**Issue by mariobehling** [orgmanager/orgmanager#384]
The hosted version at https://orgmanager.miguelpiedrafita.com/ is currently unavailable.

Error Message in Chromium:
> This page isn’t working
orgmanager.miguelpiedrafita.com redirected you too many times.
Try clearing your cookies.

Error in Firefox
> The page isn’t redirecting properly
An error occurred during a connection to orgmanager.miguelpiedrafita.com.
This problem can sometimes be caused by disabling or refusing to accept cookies.

**Comment by m1guelpf** [comment]
@mariobehling Yeah, got a few mails today about this. I'm AFK, but will make sure it's up again before monday. Thanks for reporting!

**Comment by m1guelpf** [comment]
@mariobehling We're up again! Thanks for reporting!
