### ISSUE TITLE
Allow custom message when joined organization

### ISSUE THREAD

**Issue by jancborchardt** [orgmanager/orgmanager#48]
As already mentioned in https://github.com/opensourcedesign/organization/issues/50#issuecomment-281425504

> is there also an easy way to have the visibility of people set to »Public« by default? The current standard of »Private« is a bit annoying because we have to ask everyone.

@m1guelpf you said

>  it would not be possible as the user needs to accept the invitation before we can modify status via the API

It’s ok to do it afterwards too. :) Ideally there would be some prodding to set it to Public, but of course with a confirmation. But most people sadly don’t change the default and then it just is not visible. :\

**Comment by m1guelpf** [comment]
@jancborchardt As I said, the github API doesn't allow to change visibility for security reasons. Anyway, I'll recheck that later.

**Comment by m1guelpf** [comment]
@jancborchardt API documentation for making user membership public:
https://developer.github.com/v3/orgs/members/#publicize-a-users-membership
It clearly says that only the user can make himself public... 😞

**Comment by jancborchardt** [comment]
@m1guelpf ok so don’t close this. ;) We can simply offer a switch to people for this, right? :)

**Comment by m1guelpf** [comment]
@jancborchardt That would broke the simplicity of the application... It would require the users to link their Github account and give permission th organizations...

**Comment by m1guelpf** [comment]
@jancborchardt I don't think OrgManager is made for this rigth now. Maybe this can be a cool thing one GitHub adds a better way to do it. Closing it for now.

**Comment by jancborchardt** [comment]
Maybe it’s just a little note people can be given? Like, simply a link to the search of their own name on the People page like: https://github.com/orgs/opensourcedesign/people?utf8=%E2%9C%93&query=m1guelpf

Simply saying
> Remember to set your visibility from private to **public** at [github.com/orgs/opensourcedesign/people](https://github.com/orgs/opensourcedesign/people?utf8=%E2%9C%93&query=m1guelpf) :)

**Comment by m1guelpf** [comment]
I'll look into it :smile:

**Comment by m1guelpf** [comment]
@jancborchardt You can now customize the message on the organization settings page!
