### ISSUE TITLE
Join flow

### ISSUE THREAD

**Issue by jancborchardt** [orgmanager/orgmanager#51]
Of course best would be to not need the captcha at all, but I understand the uses. But you are able to click the »Join« button without putting in a username nor checking the captcha. You get a big error on the top. Best would be to deactivate the Join button until both is filled out.

Ideally having a tooltip when hovering the join button saying »Please fill out the username« and then »Please check the "I am not a robot" checkbox above«.

**Comment by m1guelpf** [comment]
@jancborchardt I am a backend engineer...
I added a frontend design job to the OpenSourceDesign jobs page, and I am waiting for someone to help...
This could also be fixed with AJAX validation, but I am still learning how to do that...

**Comment by jancborchardt** [comment]
Awesome, great on adding it to the Open Source Design job board! :) That’s exactly what it is for.
