### ISSUE TITLE
Migration fails for MySQL version lower than 5.7

### ISSUE THREAD

**Issue by IDTitanium** [orgmanager/orgmanager#510]
## Expected Behavior

Migration should run smoothly

## Current Behavior
Migration fails after first migration (users table)

## Possible Solution
Adding schema default string length the boot function of app service provider

## Steps to Reproduce (for bugs)

1. Use MySQL DB less than 5.7 (5.6 exactly)

2.

3.

4.

## Your Environment
MySQL on docker

* Version used:

* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):

* Server type and version:
Server version:         5.6.42 MySQL Community Server (GPL)
Protocol version:       10
Connection:             Localhost via UNIX socket

* Operating System and version:

* Link to your project:

**Comment by m1guelpf** [comment]
Users should use a db compatible with the project
