### ISSUE TITLE
Bad Gateway : Broken Link

### ISSUE THREAD

**Issue by Mayank-Khurmai** [orgmanager/orgmanager#542]
@RichardLitt @samrichca @piamancini @joffreycarle @limonte 
https://orgmanager.unmarkdocs.co/contributing is Broken with Bad Gateway Error

Also add me into this organisation
mayankkhurmai8@gmail.com

**Comment by RichardLitt** [comment]
@Mayank-Khurmai, the last commit on this project was in 2019. None of the people you mentioned are active in this project. Please don't do @ people unnecessarily; if there is an issue, we'll see it, if we're maintainers. As it is, I am not, and I did not need to be pinged.

I have no insight to why there is a broken gateway. 

You do not need to be added into the organization to use the code.
