### ISSUE TITLE
GitHub OAuth option in the Join page

### ISSUE THREAD

**Issue by jancborchardt** [orgmanager/orgmanager#56]
Instead of https://orgmanager.miguelpiedrafita.com/join/4183553 it would be much nicer to have https://orgmanager.miguelpiedrafita.com/join/opensourcedesign :)

Also – get a real nice domain which isn’t just a subdomain maybe. ;)

**Comment by m1guelpf** [comment]
@jancborchardt That ID is used to prevent bruteforce, but moving to org name is a good idea.
Also, I believe open-source projects should be free, but if someone wants to donate for a domain, it'd be awesome. Also, the project was created to be selfhosted, so the hosted version isn't that important.

**Comment by jancborchardt** [comment]
Yeah, I mean at least it could be optional to switch to the readable name. :)

**Comment by m1guelpf** [comment]
@jancborchardt https://github.com/m1guelpf/orgmanager/commit/d6208b8303b2acd93feeda8c1cdd7bb19a82fa0c added pretty URL! :tada: 
You can now point users to {orgmanager-url}/o/{org-name} and it'll redirect to {orgmanager-url}/join/{org-id}!

**Comment by m1guelpf** [comment]
@jancborchardt Would you be interested in something like custom domains? For example: join.opensourcedesign.net shows the OrgManager join page for OSD. (and maybe that would also make #55 unnecesary)

**Comment by jancborchardt** [comment]
Sure, that would be cool! :) Then we could add a DNS entry.

Let me know what I need to do @m1guelpf

**Comment by jancborchardt** [comment]
I think though that »Make it possible to embed input field on website« #55 would be much cooler though. :) That also gets everyone who lands on your page to get involved very quickly. Sure, with a button you could just link to the orgmanager page, but abstracting the whole thing away through just an input field or a button which launches Github auth would be even cooler.

**Comment by m1guelpf** [comment]
@jancborchardt What about a button that uses GitHub OAuth to get the user username and then invites them?

**Comment by jancborchardt** [comment]
Sounds pretty good, like a very simple flow! :)

**Comment by m1guelpf** [comment]
Blocked by #249

**Comment by m1guelpf** [comment]
Closed in favour of https://github.com/orgmanager/orgmanager/issues/277
