### ISSUE TITLE
OrgManager Rebranding

### ISSUE THREAD

**Issue by m1guelpf** [orgmanager/orgmanager#81]
pinging @elioqoshi

**Comment by m1guelpf** [comment]
@elioqoshi Tagged this `v4.0`
Any updates?

**Comment by elioqoshi** [comment]
Well... there was no brief at all about this, so not sure how I can help when you can't help me help you :/

I can come up with a logo but having the designer to figure out stuff on his own isn't the best approach I fear.

**Comment by elioqoshi** [comment]
This is what I have until now. Maybe you get the reference here, maybe it's too subtle (which wouldn't be a problem). Font is Overpass, which is used by Red Hat. It's open source of course.

What do you think?

![draft-01](https://cloud.githubusercontent.com/assets/5436686/23877279/d4712c6a-0841-11e7-9949-d6b5cf00f923.jpg)

**Comment by m1guelpf** [comment]
@elioqoshi The design looks fantastic!

> Well... there was no brief at all about this, so not sure how I can help when you can't help me help you :/
I can come up with a logo but having the designer to figure out stuff on his own isn't the best approach I fear.

Sorry, I have never worked with a designer before 😞. How can I help you?

**Comment by elioqoshi** [comment]
That's okay. If this works for you (and I'm happy with it myself as it's taking a bit of inspiration from the git logo) then it should be all good. 

I could do the landing page design as well and someone else can implement the frontend

**Comment by elioqoshi** [comment]
![landing page-01](https://cloud.githubusercontent.com/assets/5436686/23894194/79f7fa4c-08a1-11e7-9fda-5a45530479cb.jpg)

This is how the landing page would look like (just updated font and logo)

**Comment by m1guelpf** [comment]
@elioqoshi Looks awesome!

**Comment by m1guelpf** [comment]
@elioqoshi Could you also provide the logo without text?

**Comment by elioqoshi** [comment]
Sure, I will attach push the source files

**Comment by afnizarnur** [comment]
Awesome work! @elioqoshi

**Comment by m1guelpf** [comment]
@elioqoshi 
> Sure, I will push the source files

If you want, I can create a branding repo under the orgmanager organization and give you access.

**Comment by elioqoshi** [comment]
@m1guelpf yeah please, let's do that

**Comment by m1guelpf** [comment]
@elioqoshi Invited!

**Comment by elioqoshi** [comment]
All uploaded into the repo, feel free to check :)

Also, for profile pictures (organization i.e.) feel free to use this:

![avatar](https://cloud.githubusercontent.com/assets/5436686/23991730/a1853d64-0a3a-11e7-82af-0fae86eb3820.png)

**Comment by m1guelpf** [comment]
@elioqoshi Thank you!
